2025-03-05 21:22:52,536 - INFO - ===== 应用程序启动 =====
2025-03-05 21:22:52,537 - INFO - 日志文件: logs\log_20250305_212252.txt
2025-03-05 21:22:59,494 - INFO - 开始执行脚本: code\1.3.py
2025-03-05 21:22:59,647 - ERROR - [错误] Traceback (most recent call last):
2025-03-05 21:22:59,649 - ERROR - [错误]   File "C:\Users\Administrator.DESKTOP-1B3PH7R\Desktop\测试\code\1.3.py", line 10, in <module>
2025-03-05 21:22:59,651 - ERROR - [错误]     raise Exception("该脚本在2025年2月25日之后无法使用。")
2025-03-05 21:22:59,669 - ERROR - [错误] Exception: 该脚本在2025年2月25日之后无法使用。
2025-03-05 21:22:59,695 - WARNING - 脚本 code\1.3.py 执行结束，但返回代码非零 (返回代码: 1)
